config/routes.rb
Shop::Application.routes.draw do
  get 'admin' => "admin#index"

  controller :sessions do
    get     'login' => :new
    post    'login' => :create
    delete  'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  root to: 'store#index'

end

app/views/layouts/_footer.html.slim
footer
	.left-text
		a href="mailto:piton4eg@mail.ru" Сообщить об ошибке 
	nav
		ul
			li = link_to "О каталоге", about_path
			li Телефон: 111-111

app/views/layouts/_header.html.slim
header class="navbar navbar-fixed-top navbar-inverse"
	.navbar-inner
		.container
			a class="brand" id="logo" href=root_path Интернет-каталог
			nav
				ul class="nav pull-right nav-pills"
					li = link_to "О каталоге", about_path
					li = link_to "Каталог", products_path
					li = link_to "Справка", help_path

app/views/layouts/application.html.slim
/# coding: utf-8
doctype html
html
  head
    title = full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    /[if lt IE 9] script src="http://html5shim.googlecode.com/svn/trunk/html5.js"
  body
    = render 'layouts/header'
    .container
      .row
        .span9
          - flash.each do |key, value|
            = content_tag(:div, value, class: "alert alert-#{key}")
          #store
            = yield
        .span3
          - if @cart
            = hidden_div_if(@cart.line_items.empty?, id: 'cart') do
              = render @cart
            end

          - if session[:user_id]
            ul
              li = link_to 'Заказы', orders_path
              li = link_to 'Продукты', products_path
              li = link_to 'Пользователи', users_path
            = button_to 'Выйти', logout_path, method: :delete

      = render 'layouts/footer'